import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from "../Components/Footer"
import Providers from './providers'
import Theme from '@/Components/Theme'
import Header from '@/Components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en" dir='ltr' suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-[#20232a]`} suppressHydrationWarning>
        <Providers>

          <Header/>
          <main className='mx-auto mt-40 mb-24 max-w-3xl px-6 w-full grow text-gray-500'>

          {children}  
          </main>
          <Footer />

        </Providers>
      </body>

    </html>

  )
}
